name: measuremancer CI
on:
  push:
    paths:
      - 'tests/**'
      - '**'
      - 'measuremancer.nimble'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'tests/**'
      - '**'
      - 'measuremancer.nimble'
      - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: [version-1-4, version-1-6, devel]
        target: [linux, macos, windows]
        include:
          - target: linux
            builder: ubuntu-latest
          - target: macos
            builder: macos-latest
          - target: windows
            builder: windows-latest
    name: '${{ matrix.target }} (${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: measuremancer

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.branch }}

      - name: Setup nimble & deps
        shell: bash
        run: |
          cd measuremancer
          nimble refresh -y
          nimble install -y

      - name: Run tests
        shell: bash
        run: |
          cd measuremancer
          nimble testDeps
          nimble -y test

      - name: Build docs
        if: ${{ matrix.docs == 'true' && matrix.target == 'linux' }}
        shell: bash
        run: |
          cd measuremancer
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --project --outdir:docs \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            measuremancer.nim
          # Ignore failures for older Nim
          cp docs/{the,}index.html || true

      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.target == 'linux' && matrix.branch == 'devel'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: measuremancer/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
